apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: webapp.abhyas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app-stable-svc
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: webapp.abhyas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app-canary-svc
                port:
                  number: 80
