apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-green
  labels:
    app: web-app
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      env: green
  template:
    metadata:
      labels:
        app: web-app
        env: green
        version: v2
    spec:
      containers:
        - name: nginx
          image: nginx:1.28
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 8
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 13
            timeoutSeconds: 4
            failureThreshold: 3
